// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OhV97vR5EXmYEW2WEmer9Cw_yH1Rmj4',
    appId: '1:504856430606:web:6ed8a491d7a94526f4945f',
    messagingSenderId: '504856430606',
    projectId: 'chat-app-4fa26',
    authDomain: 'chat-app-4fa26.firebaseapp.com',
    databaseURL: 'https://chat-app-4fa26-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-4fa26.appspot.com',
    measurementId: 'G-2EVB83P9TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW3GpZ6P1tsLnMY_Y4pqKbbj_uJy259Vo',
    appId: '1:504856430606:android:e7f7b70b74fa99b0f4945f',
    messagingSenderId: '504856430606',
    projectId: 'chat-app-4fa26',
    databaseURL: 'https://chat-app-4fa26-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-4fa26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxIljtNQbahR0uUZzfxC91wXZ5YwszXo',
    appId: '1:504856430606:ios:9c73883b6d900359f4945f',
    messagingSenderId: '504856430606',
    projectId: 'chat-app-4fa26',
    databaseURL: 'https://chat-app-4fa26-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-4fa26.appspot.com',
    iosClientId: '504856430606-s92r01rb6sc2md67s5qpsuunc8fspr69.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxIljtNQbahR0uUZzfxC91wXZ5YwszXo',
    appId: '1:504856430606:ios:9c73883b6d900359f4945f',
    messagingSenderId: '504856430606',
    projectId: 'chat-app-4fa26',
    databaseURL: 'https://chat-app-4fa26-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-4fa26.appspot.com',
    iosClientId: '504856430606-s92r01rb6sc2md67s5qpsuunc8fspr69.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
